import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import {
  dedup,
  prune,
  weld,
  simplify,
  simplifyPrimitive,
  quantize,
  resample,
  reorder,
} from '@gltf-transform/functions';
import { MeshoptSimplifier, MeshoptEncoder } from 'meshoptimizer';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createHash } from 'node:crypto';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../../', import.meta.url));
const generated = path.join(root, 'rebuild/generated');
const output = path.join(root, 'public/assets-v2');
await mkdir(output, { recursive: true });
await Promise.all([MeshoptSimplifier.ready, MeshoptEncoder.ready]);
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS);
const contract = JSON.parse(await readFile(path.join(generated, 'scene-contract.json'), 'utf8'));
const report = { version: 2, assets: {} };
function stats(doc) {
  const r = doc.getRoot();
  let vertices = 0,
    triangles = 0,
    primitives = 0;
  for (const mesh of r.listMeshes())
    for (const p of mesh.listPrimitives()) {
      vertices += p.getAttribute('POSITION').getCount();
      triangles += (p.getIndices()?.getCount() ?? p.getAttribute('POSITION').getCount()) / 3;
      primitives++;
    }
  const visible = {};
  for (const variant of contract.outfits)
    visible[variant] = r
      .listNodes()
      .filter(
        (n) =>
          n.getMesh() &&
          (n.getExtras().variants === 'all' ||
            String(n.getExtras().variants ?? '')
              .split(',')
              .includes(variant)),
      )
      .reduce((n, node) => n + node.getMesh().listPrimitives().length, 0);
  return {
    vertices,
    triangles,
    primitives,
    materials: r.listMaterials().length,
    textures: r.listTextures().map((t) => ({ name: t.getName(), size: t.getSize() })),
    clips: r.listAnimations().map((a) => a.getName()),
    drawCallsByOutfit: visible,
  };
}
for (const name of ['characters', 'room']) {
  const input = path.join(generated, `${name}-raw.glb`);
  const doc = await io.read(input);
  const before = stats(doc);
  await doc.transform(dedup(), weld(), resample(), prune({ keepExtras: true }));
  if (name === 'characters') {
    // Keep the approved wrap edge intact. Independent position quantization or
    // simplifying this nearly touching shell produces visible rim artifacts.
    for (const node of doc.getRoot().listNodes()) {
      if (node.getExtras().asset_group === 'Base_wrap_arms') continue;
      for (const p of node.getMesh()?.listPrimitives() ?? [])
        simplifyPrimitive(p, {
          simplifier: MeshoptSimplifier,
          ratio: 0.46,
          error: 0.0007,
          lockBorder: true,
        });
    }
    await doc.transform(
      quantize({
        pattern: /^(NORMAL|TEXCOORD|WEIGHTS|COLOR)/,
        quantizeNormal: 10,
        quantizeTexcoord: 12,
        quantizeWeight: 12,
      }),
    );
  } else {
    await doc.transform(
      simplify({ simplifier: MeshoptSimplifier, ratio: 0.65, error: 0.0007, lockBorder: true }),
      quantize({ quantizePosition: 14, quantizeNormal: 10 }),
    );
  }
  // Portable integer attributes reduce GPU buffers, without a runtime decoder.
  await doc.transform(reorder({ encoder: MeshoptEncoder }), dedup(), prune({ keepExtras: true }));
  const bytes = await io.writeBinary(doc);
  await writeFile(path.join(output, `${name}.glb`), bytes);
  report.assets[name] = {
    before,
    after: stats(doc),
    sourceBytes: (await readFile(input)).byteLength,
    bytes: bytes.byteLength,
    hash: createHash('sha256').update(bytes).digest('hex').slice(0, 12),
  };
}
await writeFile(path.join(output, 'scene-contract.json'), JSON.stringify(contract, null, 2) + '\n');
await writeFile(path.join(output, 'asset-report.json'), JSON.stringify(report, null, 2) + '\n');
for (const name of [...contract.outfits, 'room']) {
  try {
    const png = await readFile(path.join(generated, name + '.png'));
    await sharp(png)
      .resize(name === 'room' ? 800 : 240)
      .webp({ quality: 82 })
      .toFile(path.join(output, name + '-preview.webp'));
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
}
await mkdir(path.join(root, 'src/generated'), { recursive: true });
await writeFile(
  path.join(root, 'src/generated/assets.ts'),
  '// Generated by npm run assets:optimize. Do not edit by hand.\nexport const assetContract = ' +
    JSON.stringify(contract, null, 2) +
    ' as const;\nexport const assetReport = ' +
    JSON.stringify(report, null, 2) +
    ' as const;\n',
);
console.log(JSON.stringify(report, null, 2));
